name: alumni_app
description: Alumni Management System like LinkedIn
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.0.0

  # Supabase
  supabase_flutter: ^2.5.8

  # Local DB
  sqflite: ^2.3.0
  path: ^1.8.3

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2

  # Agora (video/audio calls)
  agora_rtc_engine: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
